volumes:
  pg-data:

services:
  app:
    container_name: quarkusdev
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - pg.env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    container_name: pgdb
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - pg.env
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./initdb.d:/docker-entrypoint-initdb.d
